[package]
name = "teo-language-server-wasm"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.87"
wasm-logger = { version = "0.2.0", optional = true }
pest = "2.7.3"
pest_derive = "2.7.3"